<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="P_InkSystem" Id="{d9a0afbc-418e-46e5-90d4-34e152ff11fa}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_InkSystem
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_ISS();
P_Stirrer_WastePump();



]]></ST>
    </Implementation>
    <LineIds Name="P_InkSystem">
      <LineId Id="8" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="49" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>